# Generated by Django 5.2.7 on 2025-10-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_catrgory_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catrgory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catrgory',
            new_name='categoray',
        ),
    ]
