# Generated by Django 5.2.7 on 2025-10-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedbak',
            field=models.CharField(),
        ),
    ]
