# Generated by Django 5.2.7 on 2025-10-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedbak',
            new_name='feedback',
        ),
    ]
